swagger: "2.0"
info:
  title: on-network api
  version: "0.0.1"
consumes:
- application/json

definitions:
  Error:
    properties:
      code:
        format: int32
        type: integer
      fields:
        type: string
      message:
        type: string
  ErrorResponse:
    properties:
      message:
        type: string
      errors:
        items:
          type: string
        type: array
    required:
    - message
  About:
    properties:
      name:
        type: string
    required:
    - name
  UpdateSwitch:
    type: object
    required:
    - endpoint
    - imageURL
    - switchModel
    properties:
      endpoint:
        $ref: "#/definitions/SwitchEndpoint"
      imageURL:
        type: string
      switchModel:
        type: string
  SwitchEndpoint:
    type: object
    required:
    - ip
    - username
    - password
    - switchType
    properties:
      ip:
        type: string
      username:
        type: string
      password:
        type: string
      switchType:
        type: string
  Switch:
      type: object
      required:
      - endpoint
      properties:
        endpoint:
          $ref: "#/definitions/SwitchEndpoint"

securityDefinitions:
  APIKeyHeader:
    type: apiKey
    in: header
    name: authorization

security:
- APIKeyHeader: []

paths:
  /about:
    get:
      description: Information about on-network
      operationId: aboutGet
      responses:
        200:
          description: Successfully retrieved about
          schema:
            $ref: '#/definitions/About'
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Get about
      tags:
        - /about

  /updateSwitch:
    post:
      description: Update switch firmware based on specified switch type and firmware image
      operationId: updateSwitch
      parameters:
      - name: body
        in: body
        schema:
          $ref: "#/definitions/UpdateSwitch"
      responses:
        201:
          description: Successfully issued update switch firmware
        default:
          description: Error
          schema:
            $ref: '#/definitions/ErrorResponse'
      summary: Update switch firmware
      tags:
      - /updateSwitch

  /switchConfig:
    post:
      description: Get switch running config
      operationId: switchConfig
      parameters:
      - name: body
        in: body
        schema:
          $ref: "#/definitions/Switch"
      responses:
        200:
          description: Successfully returned switch running config
        default:
          description: Error
          schema:
            $ref: '#definitions/ErrorResponse'
      summary: Get switch running config
      tags:
      - /switchConfig

  /switchFirmware:
     post:
       description: Get switch Firmware Version
       operationId: switchFirmware
       parameters:
       - name: body
         in: body
         schema:
           $ref: "#/definitions/Switch"
       responses:
         200:
           description: Successfully returned switch firmware version
         default:
           description: Error
           schema:
             $ref: '#definitions/ErrorResponse'
       summary: Get switch Firmware Version
       tags:
       - /switchFirmware